openapi: 3.0.0
info:
  title: DCSA.org Interface Track Standards Open Api Specification
  description: Open Api Specification for the DCSA Interface Tracking Standards
  contact:
    name: Digital Container Shipping Association (DCSA)
    url: https://dcsa.org
    email: info@dcsa.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
servers:
- url: /
tags:
- name: Shipments
  description: Shipment operations
- name: Transports
  description: Transport operations
- name: Equipments
  description: Equipment operations
paths:
  /shipments/{bookingReference}:
    get:
      tags:
      - Shipments
      summary: Find shipment by Booking Reference
      description: Returns a single shipment
      parameters:
      - name: bookingReference
        in: path
        description: Booking Reference of shipment to return
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/bookingReference'
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Invalid Booking Reference supplied
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Booking Reference not found
  /shipments/billOfLadingNumber={billOfLadingNumber}:
    get:
      tags:
      - Shipments
      summary: Find shipment by Bill of Lading
      description: Returns a single shipment
      parameters:
      - name: billOfLadingNumber
        in: path
        description: Bill of Lading of shipment to return
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/billOfLadingNumber'
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Invalid Booking Reference supplied
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Booking Reference not found
  /shipments/{bookingReference}/events:
    get:
      tags:
      - Shipments
      summary: Find events by Booking Reference
      description: Returns all events of a single shipment
      parameters:
      - name: bookingReference
        in: path
        description: Booking Reference of shipment to return
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/bookingReference'
      - name: equipmentReference
        in: query
        description: Equipment Reference of equipment to filter events by
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/equipmentReference'
      - name: transportReference
        in: query
        description: Transport Reference of transport to filter events by
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/transportReference'
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: Invalid Booking Reference supplied
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Booking Reference not found
  /transports/{transportReference}:
    get:
      tags:
      - Transports
      summary: Find transports by Transport Reference
      description: Returns a single transport
      parameters:
      - name: transportReference
        in: path
        description: Transport Reference of transport to return
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/transportReference'
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        "400":
          description: Invalid Transport Reference supplied
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Transport Reference not found
  /equipments/{equipmentReference}:
    get:
      tags:
      - Equipments
      summary: Find equipments by Equipment Reference
      description: returns a single equipment
      parameters:
      - name: equipmentReference
        in: path
        description: Equipment Reference of equipment to return
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/equipmentReference'
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
        "400":
          description: Invalid Equipment Reference supplied
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Equipment Reference not found
  /equipments/{equipmentReference}/activeShipmentEvents:
    get:
      tags:
      - Equipments
      summary: Find active shipment events related to Equipment Reference
      description: Returns a list of active events for a single equipment
      parameters:
      - name: equipmentReference
        in: path
        description: Equipment Reference of the active events to return
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/equipmentReference'
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "400":
          description: Invalid Equipment Reference supplied
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Equipment Reference not found
components:
  schemas:
    shipment:
      type: object
      properties:
        bookingReference:
          $ref: '#/components/schemas/bookingReference'
        billOfLadingNumber:
          $ref: '#/components/schemas/billOfLadingNumber'
        bookingDateTime:
          $ref: '#/components/schemas/bookingDateTime'
        carrierCode:
          $ref: '#/components/schemas/carrierCode'
        shipperName:
          $ref: '#/components/schemas/shipperName'
        consigneeName:
          $ref: '#/components/schemas/consigneeName'
        origin:
          $ref: '#/components/schemas/origin'
        destination:
          $ref: '#/components/schemas/destination'
        actualDeliveryDateTime:
          $ref: '#/components/schemas/actualDeliveryDateTime'
        eventsLink:
          $ref: '#/components/schemas/eventsLink'
      description: The shipment entity is a reference entity that describes a shipment
        in the context of tracking of shipments.
    event:
      type: object
      properties:
        bookingReference:
          $ref: '#/components/schemas/bookingReference'
        eventDateTime:
          $ref: '#/components/schemas/eventDateTime'
        eventID:
          $ref: '#/components/schemas/eventID'
        eventStatus:
          $ref: '#/components/schemas/eventStatus'
        eventType:
          $ref: '#/components/schemas/eventType'
      description: The event entity is described as a generalization of all the specific
        event categories. An event always takes place in relation to a shipment and
        can additionally be linked to a transport or an equipment
    transportEquipmentEvent:
      description: The transport equipment event entity is a specialization of the
        event entity to support specification of data that applies to both transport
        and equipment events.
      allOf:
      - $ref: '#/components/schemas/event'
      - type: object
        properties:
          equipmentReference:
            $ref: '#/components/schemas/equipmentReference'
          transportReference:
            $ref: '#/components/schemas/transportReference'
          facilityType:
            $ref: '#/components/schemas/facilityType'
          location:
            $ref: '#/components/schemas/location'
          sublocation:
            $ref: '#/components/schemas/sublocation'
          transportLink:
            $ref: '#/components/schemas/transportLink'
          equipmentLink:
            $ref: '#/components/schemas/equipmentLink'
    transportEvent:
      description: The transport event entity is a specialization of the event entity
        to support specification of data that only applies to a transport event.
      allOf:
      - $ref: '#/components/schemas/event'
      - type: object
        properties:
          transportReference:
            $ref: '#/components/schemas/transportReference'
          facilityType:
            $ref: '#/components/schemas/facilityType'
          location:
            $ref: '#/components/schemas/location'
          sublocation:
            $ref: '#/components/schemas/sublocation'
          transportLink:
            $ref: '#/components/schemas/transportLink'
    equipmentEvent:
      description: The equipment event entity is a specialization of the event entity
        to support specification of data that only applies to an equipment event.
      allOf:
      - $ref: '#/components/schemas/event'
      - required:
        - emptyIndicator
        - equipmentLink
        - equipmentReference
        type: object
        properties:
          equipmentReference:
            $ref: '#/components/schemas/equipmentReference'
          emptyIndicator:
            $ref: '#/components/schemas/emptyIndicator'
          equipmentLink:
            $ref: '#/components/schemas/equipmentLink'
    shipmentEvent:
      description: The shipment event entity is a specialization of the event entity
        to support specification of data that only applies to a shipment event.
      allOf:
      - $ref: '#/components/schemas/event'
      - required:
        - informationType
        type: object
        properties:
          informationType:
            $ref: '#/components/schemas/informationType'
    events:
      required:
      - bookingReference
      - events
      - shipmentLink
      type: object
      properties:
        bookingReference:
          $ref: '#/components/schemas/bookingReference'
        shipmentLink:
          $ref: '#/components/schemas/shipmentLink'
        events:
          type: array
          items:
            discriminator:
              propertyName: event
            anyOf:
            - $ref: '#/components/schemas/transportEvent'
            - $ref: '#/components/schemas/shipmentEvent'
            - $ref: '#/components/schemas/equipmentEvent'
            - $ref: '#/components/schemas/transportEquipmentEvent'
      description: A list of event-subentity objects for a single Booking Reference
    equipmentEvents:
      required:
      - bookingReference
      - events
      - shipmentLink
      type: object
      properties:
        bookingReference:
          $ref: '#/components/schemas/bookingReference'
        shipmentLink:
          $ref: '#/components/schemas/shipmentLink'
        events:
          type: array
          items:
            discriminator:
              propertyName: event
            anyOf:
            - $ref: '#/components/schemas/equipmentEvent'
            - $ref: '#/components/schemas/transportEquipmentEvent'
      description: A list of event-subentities that are associated with a piece of
        equipment
    equipment:
      required:
      - equipmentNumber
      - equipmentType
      type: object
      properties:
        equipmentNumber:
          $ref: '#/components/schemas/equipmentNumber'
        equipmentType:
          $ref: '#/components/schemas/equipmentType'
      description: The equipment entity is a reference entity that describes an equipment
        in the context of tracking of shipments. An event can contain a reference
        to the equipment entity if it is of the appropriate event category.
    transport:
      required:
      - meansOfTransport
      - transportReference
      - vesselNumber
      - voyageNumber
      type: object
      properties:
        meansOfTransport:
          $ref: '#/components/schemas/meansOfTransport'
        transportReference:
          $ref: '#/components/schemas/transportReference'
        vesselNumber:
          $ref: '#/components/schemas/vesselNumber'
        voyageNumber:
          $ref: '#/components/schemas/voyageNumber'
      description: The transport entity is a reference entity that describes a transport
        in the context of tracking of shipments. An event can contain a reference
        to the transport entity if it is of the appropriate event category.
    metadata:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/metadata_metadata'
      description: The metadata entity is an entity that describes the responses metadata
    bookingReference:
      type: string
      description: Booking Reference that uniquely identifies a shipment
      example: YCH698840
    transportReference:
      type: string
      description: The reference for the means of transport that will be used to transport
        the equipment
      example: "5"
    equipmentReference:
      type: string
      description: The unique identifier for the equipment
      example: EQ APZU4812090
    billOfLadingNumber:
      type: string
      description: Bill of Lading that uniquely identifies a shipment
      example: "855230418"
    facilityType:
      type: string
      description: Facility Types, two characters to define the specific type of sublocation
      example: PT
    location:
      type: string
      description: Location code
      example: USNYC
    sublocation:
      type: string
      description: Event sublocation code
      example: AEJEADPWJA
    emptyIndicator:
      type: boolean
      description: Status denoting whether the equipment is empty or not at the time
        of the event
      example: false
    informationType:
      type: string
      description: The code to identify the type of information that is related to
        the Shipment
      example: Cargo Release Message Issued
    equipmentNumber:
      type: string
      description: '*MISSING DESCRIPTION* This attribute only exists in the class
        diagram at the moment'
      example: "17"
    equipmentType:
      type: string
      description: Unique Code for the different container "size/type" used for transporting
        commodities
      example: 10G0
    meansOfTransport:
      type: string
      description: A code specifying a type of transport means
      example: "5"
    vesselNumber:
      type: string
      description: The unique reference for a registered Vessel
      example: "9188403"
    voyageNumber:
      type: string
      description: The unique reference for the voyage as defined by the vessel operator
      example: "20"
    eventDateTime:
      type: string
      description: Event Date Time, following the RFC3339 standard, in the format
        YYYY-MM-DDTHH:MM:SSZ
      format: date-time
    eventID:
      type: string
      description: Equipment Event ID/Transport Event ID/Shipment Event ID
      example: "1"
    eventStatus:
      type: string
      description: Event Status Code (Planned, Estimated or Actual)
      example: ACT
    eventType:
      type: string
      description: Unique identifier for Event Type Code
      example: ARI
    bookingDateTime:
      type: string
      description: Booking Date Time, following the RFC3339 standard, in the format
        YYYY-MM-DDTHH:MM:SSZ
      format: date-time
    carrierCode:
      type: string
      description: Carrier SCAC code
      example: MAEU
    shipperName:
      type: string
      description: Shipper name
      example: Computer Corp.
    consigneeName:
      type: string
      description: Unique identifier for Event Type Code
      example: ARI
    origin:
      type: string
      description: Collection origin
      example: USNYC
    destination:
      type: string
      description: Delivery destination
      example: USNYC
    actualDeliveryDateTime:
      type: string
      description: Actual Delivery Date Time, following the RFC3339 standard, in the
        format YYYY-MM-DDTHH:MM:SSZ
      format: date-time
    eventsLink:
      pattern: /shipments/[A-z0-9-%]+/events
      type: string
      description: A relative url to the events for the booking reference
      example: /shipments/YCH698840/events
    transportLink:
      pattern: /transports/[A-z0-9-%]+
      type: string
      description: A relative URL to the transport for the transport reference
      example: /transports/5
    equipmentLink:
      pattern: /equipments/[A-z0-9-%]+
      type: string
      description: A relative URL to the equipment for the equipment reference
      example: /equipments/EQ%20APZU4812090
    shipmentLink:
      pattern: /shipments/[A-z0-9-%]+
      type: string
      description: A relative URL to the shipment for the booking reference
      example: /shipments/YCH698840
    inline_response_200:
      allOf:
      - $ref: '#/components/schemas/shipment'
      - $ref: '#/components/schemas/metadata'
    inline_response_200_1:
      allOf:
      - $ref: '#/components/schemas/events'
      - $ref: '#/components/schemas/metadata'
    inline_response_200_2:
      allOf:
      - $ref: '#/components/schemas/transport'
      - $ref: '#/components/schemas/metadata'
    inline_response_200_3:
      allOf:
      - $ref: '#/components/schemas/equipment'
      - $ref: '#/components/schemas/metadata'
    inline_response_200_4:
      allOf:
      - $ref: '#/components/schemas/equipmentEvents'
      - $ref: '#/components/schemas/metadata'
    metadata_metadata:
      required:
      - dcsaVersion
      - self
      type: object
      properties:
        dcsaVersion:
          type: string
          description: Version code, specifying the version of the implemented Open
            API Specification
          example: 1.0.0
        self:
          type: string
          description: Relative url of the current endpoint
          example: /shipments/YCH698840
